version: '3'
services:
  web:
    build: sreality
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sreality
    volumes:
      - ./postgres_init.sql:/docker-entrypoint-initdb.d/postgres_init.sql